### PR TITLE
Implement user promotion

### PR DESCRIPTION
**Pull request by technowar**

### CODE REVIEW

**Comment by elizar** [comment]
why?

**Comment by technowar** [comment]
Why, what?

**Comment by elizar** [comment]
#85

**Comment by elizar** [comment]
LGTM so far :+1:

**Comment by technowar** [comment]
Ahh. Ako gi fetch iya code, since d man niya matiwas kay hinay daw internet.

**Comment by elizar** [comment]
ahhh ok

**Pull request merged**
