### PR TITLE
Initial Auth implementation

### PR DESCRIPTION
**Pull request by technowar**

### CODE REVIEW

**Comment by elizar** [comment]
payts nana jom2x ayaw lang gamit config.json, try lang og kuha sa key og secret gikan sa `process.env`.

**Comment by elizar** [comment]
CC @technowar @XanderDwyl

**Comment by elizar** [comment]
and I think di ta kailangan og passport session, naa na may session gi gamit nato kita ka anang redis etc?

**Comment by elizar** [comment]
@technowar close lang ni nako dodong, kato lang grant ato gamiton :+1: 

CC @XanderDwyl @rohitdaryanani batig nawng!

**Comment by rohitdaryanani** [comment]
:-1:

**Comment by technowar** [comment]
Noted! Ty.

**Pull request closed without merging**
