### PR TITLE
Fixes dockerized test

### PR DESCRIPTION
**Pull request by elizar**
Signed-off-by: Elizar Pepino <jupenz@gmail.com>

### CODE REVIEW

**Comment by elizar** [comment]
Palihug kog review and merge bitches @rohitdaryanani @technowar @XanderDwyl 

This should fix `make tdd` problem

**Comment by technowar** [comment]
:+1:

**Comment by XanderDwyl** [comment]
looks good

**Comment by elizar** [comment]
Will merge this bitches :baby_chick:

**Pull request merged**
